# Generated by Django 5.2.1 on 2025-05-28 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_cuisine_diet_difficulty_ingredient_mealtype_tag_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='difficulty',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='myapp_recip_user_id_12e30d_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='myapp_recip_difficu_b2e825_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='myapp_recip_cuisine_2bd243_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='myapp_recip_meal_ty_80f2a8_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='myapp_recip_created_0b8f44_idx',
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='diets',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='favorited_by',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mealtype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.cuisine'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.difficulty'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mealtype'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='myapp.recipe'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
