# Generated by Django 5.2.1 on 2025-05-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_difficulty_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If checked, this recipe will be visible on the main page'),
        ),
    ]
