# Generated by Django 5.2.1 on 2025-05-28 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
    ]
