# Generated by Django 5.2.1 on 2025-06-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_recipe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine',
            name='country_code',
            field=models.CharField(blank=True, help_text='ISO country code for flag display', max_length=5, null=True),
        ),
    ]
