# Generated by Django 5.2.1 on 2025-06-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='myapp.tag'),
        ),
    ]
