# Generated by Django 4.2.1 on 2025-06-23 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_blog_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeDiet',
        ),
    ]
