# Generated by Django 4.2.1 on 2025-06-24 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_delete_recipediet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diet',
        ),
    ]
